### ISSUE TITLE
Indexing Fails

### ISSUE THREAD

**Issue by gf3** [pauldowman/balisong#5]
Indexing via rake task fails:

``` shell
$ rake balisong:db:index --trace
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
** Invoke balisong:db:index (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute balisong:db:index
Creating index for branch gf3.ca
rake aborted!
undefined method `trees' for nil:NilClass
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/activesupport-3.0.10/lib/active_support/whiny_nil.rb:48:in `method_missing'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/gitmodel-0.0.6/lib/gitmodel.rb:84:in `index!'
/Users/gianni/Projects/rails/gf3.ca-balisong/lib/tasks/balisong.rake:13:in `block (3 levels) in <top (required)>'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/gianni/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/bin/rake:19:in `load'
/Users/gianni/.rvm/gems/ruby-1.9.2-p290@balisong/bin/rake:19:in `<main>'
Tasks: TOP => balisong:db:index
```

Points to this line: https://github.com/pauldowman/gitmodel/blob/45703a31c68cf02046c88327aee63003ccb0bcea/lib/gitmodel.rb#L84

**Comment by gf3** [comment]
Ahh, it's an easy fix. `balisong.rake` is trying to use the branch of the rails app as the branch for the balisong content. Which in my case are two totally different branches.

Here's the code: https://github.com/pauldowman/balisong/blob/bbfa14692201910dfe8403cb49b5981fea4b7f70/lib/tasks/balisong.rake#L11

It looks like it should be doing that from inside the content repo.

**Comment by pauldowman** [comment]
It's assuming that you're in the data directory. Definitely a bad assumption. I'll fix it.

**Comment by pauldowman** [comment]
oh, sorry, you already fixed it, I didn't read carefully. Thanks, I'll take that. :-)

**Comment by pauldowman** [comment]
Thanks Gianni!
